spring.application.name=ApiLivro

# Datasource
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ApiDeLivros
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Flyway
spring.flyway.enabled=true

# Erros
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never

api.security.token.secret={JWT_SECRET}